name: Left2Craft
version: 0.6.0
api-version: 1.16
author: Oats
main: cloud.ferguson.Left2Craft.Main
description: Hardcore Minecraft with a twist! Bring your friends back with a revival ritual
commands:
